apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "hyper-scale-ops.fullname" . }}
  labels:
    {{- include "hyper-scale-ops.labels" . | nindent 4 }}

data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}